version: "3.5"

services:
  app:
    container_name: php8
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - "9090:80"
    # networks:
    #   - php8
    depends_on:
      - db

  # Database
  db:
    image: mysql:5.7
    # container_name: mysql
    # command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'test'
      MYSQL_DATABASE: php8
      MYSQL_PASSWORD: 'test'
      MYSQL_USER: 'test'
    # networks:
    #   - mysql-phpmyadmin

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    # networks:
    #   - mysql-phpmyadmin

# networks:
#   php8:
#   mysql-phpmyadmin:

volumes:
  db_data:
