CREATE TABLE `php8`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT , 
  `email` VARCHAR(256) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL , 
  `senha` VARCHAR(256) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL , 
  `nome` VARCHAR(256) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL , 
  `nivel` VARCHAR(256) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL , UNIQUE (`id`)) ENGINE = InnoDB CHARSET=utf8 COLLATE utf8_bin;